Added the 'exclude_directories' config option
ShawnMilo/gitstats pull request #2
Opened 2016-09-22 20:34 UTC by gregfenton

2016-09-23 03:23 UTC, ShawnMilo commented on gitstats
> +    'exclude_directories': 'src/test/',
This probably shouldn't have any defaults. This would be unexpected behavior for a user who didn't read the source code.

2016-09-23 03:28 UTC, ShawnMilo commented on gitstats
> +                if any(dir in fullpath for dir in conf['exclude_directories'].split(',')):
`dir` is a keyword in Python. This should be changed to something like `path`.

There's no need to check the length -- if you iterate over the `.split()` results nothing will happen if it's empty. However, this should be a list or a tuple instead. I know the `exclude_extensions` value I hard-coded is comma-separated, but I should change that.

There should be a way to pass in directories to exclude at the command line. Or possibly with a config file, such as `.bashrc` or `.vimrc`. I'm open to either one -- preferably both. There's a TODO in there to replace getopt with argparse, so if you're feeling really ambitious you could do that.

2016-09-23 03:29 UTC, ShawnMilo requested changes
Thanks. It's a good idea! I just have a couple of notes about it.

2016-09-23 17:52 UTC, gregfenton commented on gitstats
> +                if any(dir in fullpath for dir in conf['exclude_directories'].split(',')):
Thank you for the comprehensive feedback.  I will make a few changes based on this and commit soon.

BTW: any idea on how I can test the results of my changes relatively effectively and consistently?  I can run a report against my own fairly comprehensive repos, but not sure that I can easily determine that the results are correct.

2016-11-09 17:24 UTC, merged

2016-11-09 17:24 UTC, ShawnMilo commented
Hey. Thanks for making the changes. Sorry it took me so long to get back to this.

2016-11-09 18:16 UTC, gregfenton commented
Shawn,
Thank you for all of your contributions!
Greg Fenton--
email: greg.fenton@gmail.comlinkedin: http://ca.linkedin.com/in/fentongreg
twitter: @gregfenton
-------- Original message --------From: Shawn Milochik <notifications@github.com> Date: 2016-11-09  09:24  (GMT-08:00) To: ShawnMilo/gitstats <gitstats@noreply.github.com> Cc: gregfenton <greg.fenton@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ShawnMilo/gitstats] Added the 'exclude_directories' config option (#2) 
Hey. Thanks for making the changes. Sorry it took me so long to get back to this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ShawnMilo/gitstats","title":"ShawnMilo/gitstats","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ShawnMilo/gitstats"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ShawnMilo in #2: Hey. Thanks for making the changes. Sorry it took me so long to get back to this."}],"action":{"name":"View Pull Request","url":"https://github.com/ShawnMilo/gitstats/pull/2#issuecomment-259472210"}}}